services:
  scraper-v2:
    build: .
    env_file:
      - ../app-eeina-backend/.env
    ports:
      - '6000:6000'
    networks:
      - eeina_network
    restart: always

networks:
  eeina_network:
    external: true